name:         henhen
version:      1.0.0
author:       kbmackenzie <kelly.a.betty@gmail.com>
github:       kbmackenzie/henhen
license:      GPL-3.0-only
copyright:    2024 kbmackenzie
description:  'Isolated virtual environments for CHICKEN Scheme.'

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.17.2.1 && < 5
- text >= 2.0.2 && < 2.1
- bytestring >= 0.11.5.3 && < 0.13
- containers >= 0.6.7 && < 0.7
- mtl >= 2.2.2 && < 2.4
- unordered-containers >= 0.2.19.1 && < 0.3
- filepath >= 1.4.2.2 && < 1.5
- directory >= 1.3.7.1 && < 1.4
- hashable >= 1.4.3.0 && < 1.5
- aeson >= 2.1.2.1 && < 2.2
- conduit >= 1.3.5 && < 1.4
- yaml >= 0.11.11.2 && < 0.12
- process >= 1.6.18.0 && < 1.7
- filepattern >= 0.1.3 && < 0.2
- typed-process >= 0.2.11.1 && < 0.3
- time >= 1.12.2 && < 1.13
- ansi-terminal >= 0.11.5 && < 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - HenHen
  - HenHen.Actions
  - HenHen.Cache
  - HenHen.Config
  - HenHen.Environment
  - HenHen.Packager
  generated-other-modules: Paths_henhen

executables:
  henhen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -static
    dependencies:
    - henhen
    - optparse-applicative >= 0.17.1.0 && < 0.18

tests:
  henhen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - henhen
    - hspec >= 2.10.10 && < 2.11
    - HUnit >= 1.6.2.0 && < 1.7
