name:         henhen
version:      1.0.0
author:       kbmackenzie <kelly.a.betty@gmail.com>
github:       kbmackenzie/henhen
license:      GPL-3.0-only
copyright:    2024 kbmackenzie
description:  ''

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.1
- containers >= 0.6 && < 0.7
- mtl >= 2.2 && < 2.4
- unordered-containers >= 0.2 && < 0.3
- filepath >= 1.4 && < 1.5
- directory >= 1.3 && < 1.4
- ansi-terminal >= 0.11 && < 0.12
- aeson >= 2.1 && < 2.2
- conduit >= 1.3 && < 1.4
- yaml >= 0.11 && < 0.12
- typed-process >= 0.2 && < 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  henhen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - henhen

tests:
  henhen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - henhen
